name: CI - Tests Sentiment Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupération du dépôt
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Installation de Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    # 3. Installation des dépendances
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        pip install httpx
        pip install --no-cache-dir torch==2.8.0+cpu --index-url https://download.pytorch.org/whl/cpu

    # 4. Lancement des tests
    - name: Run tests with pytest
      run: pytest -v --maxfail=1 --disable-warnings
